// BASE CLASS VISIBILITY              DERIVED CLASS VISIBILITY

//                                       PUBLIC                 PRIVATE             PROTECTED

// PRIVATE                            NOT INHERITED           NOT INHERITED       NOT INHERITED

// PROTECTED                          PROTECTED               PRIVATE             PROTECTED

// PUBLIC                             PUBLIC                  PRIVATE             PROTECTED





// EXPLAINING SECOND OF SECOND,IF THERE IS SOMETHING INSIDE PROTECTED OF THE BASE CLASS, THAN IF WE INHERIT UPRIVATELY, I.E. : PRIVATE "CLASSNAME", THE, IT BECOMES PRIVATE IN INHERTED CLASS


// ITS LIKE A FLOOR,
// MOST UPWARD = PUBLIC
// MID = PROTECTED
// MOST DOWNWARD = PRIVATE
// IF IN ANY CLASS A, ANY OF THESE FLLORS IS CHOSEN, THEN IN ITS DERIVES CLASS, THESE DATA MEMBERS CANNOT GO UPWARDS IN FLOOR, FOR EXAMPLE, IF LL N; , WE DECLARE THIS IN PROTECTED, THEN WE MAKE MANY DERIVED CLASSES, THIS CAN ONLY REMAIN EITHER PROTECTED OR DOWNWARD PRIVATE IN DERIVED CLASSES, THE DATA MEMBERS AND FUNCTIONS CANT EVER MOVE UP IN THE FLOORS
